---

id: learning

formGroups:
  - preset: selectLearning
  - preset: abstract
  - preset: learningCategory
  - preset: homepageURL
    param: {type: url}
  - preset: team
  - preset: empty
    title: uses
    param: {start: true}
  - preset: contact
    param: {phone: false}
  - widget: string
    title: date
    param: {type: date, rule: dateISO}
  - preset: empty
  - preset: empty
