---

id: learning

formGroups:
  - preset: selectLearning
  - preset: abstract
  - preset: learningType
  - preset: learningCategory
  - preset: tags
  - preset: difficulty
  - preset: homepageURL
    param: {type: url}
  - preset: contact
    param: {phone: false}
  - widget: string
    title: date
    param: {type: date, rule: dateISO}
  - preset: empty
  - preset: empty
